@baseUrl = http://localhost:5000

### Création d'un utilisateur (POST)
POST {{baseUrl}}/api/users/
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "john.doe@example.com",
  "gender": "Male",
  "ip_address": "192.168.1.1"
}

###

### Récupérer tous les utilisateurs (GET)
GET {{baseUrl}}/api/users/

###

### Mettre à jour partiellement un utilisateur (PATCH)
PATCH {{baseUrl}}/api/users/1
Content-Type: application/json

{
  "id": 1,
  "first_name": "Jonathan",
  "email": "jonathan.doe@example.com"
}

###

### Supprimer un utilisateur par ID (DELETE)
DELETE {{baseUrl}}/api/users/1

###
